name: Terraform Workflow

on:
  workflow_dispatch:
    inputs:
      proceed_with_destroy:
        description: 'Do you want to proceed with terraform destroy? (yes/no)'
        required: true
        default: 'no'
      confirm_destroy:
        description: 'Are you sure you want to proceed with terraform destroy? (yes/no)'
        required: true
        default: 'no'
jobs:
  terraform:
    name: 'Terraform'  # Name of the job
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner
    environment: development  # Specify the environment

    env:
      AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}  # Reference the environment variable for AWS region

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2  # Check out the repository code

      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v1  # Set up Terraform
        with:
          terraform_version: 1.0.0  # Specify the Terraform version

      - name: 'Debug AWS Region'
        run: echo "AWS_DEFAULT_REGION=${{ env.AWS_DEFAULT_REGION }}"  # Output the AWS region for debugging

      - name: 'Configure AWS Credentials'
        uses: aws-actions/configure-aws-credentials@v1  # Configure AWS credentials
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}  # Use the AWS access key ID from secrets
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # Use the AWS secret access key from secrets
          aws-region: ${{ env.AWS_DEFAULT_REGION }}  # Use the AWS region from the environment variable

      - name: 'Terraform Init'
        run: terraform init  # Initialize Terraform

      - name: 'Terraform Apply - BLUE - GREEN TBD' 
        run: terraform apply -auto-approve  # Apply Terraform-managed infrastructure
        
      - name: Check initial user input
        run: |
          if [ "${{ github.event.inputs.proceed_with_destroy }}" != "yes" ]; then
            echo "User chose not to proceed with terraform destroy."
            exit 0
          fi
          echo "User chose to proceed with terraform destroy."

      - name: Confirm Terraform Destroy
        if: ${{ github.event.inputs.proceed_with_destroy }} == 'yes'
        run: |
          if [ "${{ github.event.inputs.confirm_destroy }}" != "yes" ]; then
            echo "User chose not to confirm terraform destroy."
            exit 0
          fi
          echo "User confirmed to proceed with terraform destroy."

      - name: 'Terraform Destroy'
        if: ${{ github.event.inputs.confirm_destroy }} == 'yes'
        run: terraform destroy -auto-approve  # Destroy Terraform-managed infrastructure

      - name: 'Exit Message'
        if: ${{ github.event.inputs.proceed_with_destroy }} != 'yes' || ${{ github.event.inputs.confirm_destroy }} != 'yes'
        run: echo "OK Bye"