name: Terraform  # Name of the workflow

on:
  #push:
  #  branches:
  #    - main  # Trigger the workflow on push to the main branch
  #pull_request:
  #  branches:
  #    - main  # Trigger the workflow on pull request to the main branch
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  terraform:
    name: 'Terraform'  # Name of the job
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner
    environment: development  # Specify the environment
    env:
      AWS_DEFAULT_REGION: ${{ env.AWS_DEFAULT_REGION }}  # Reference the environment variable for AWS region

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2  # Check out the repository code

      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v1  # Set up Terraform
        with:
          terraform_version: 1.0.0  # Specify the Terraform version

      - name: 'Debug AWS Region'
        run: echo "AWS_DEFAULT_REGION=${{ env.AWS_DEFAULT_REGION }}"  # Output the AWS region for debugging

      - name: 'Configure AWS Credentials'
        uses: aws-actions/configure-aws-credentials@v1  # Configure AWS credentials
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}  # Use the AWS access key ID from secrets
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # Use the AWS secret access key from secrets
          aws-region: ${{ env.AWS_DEFAULT_REGION }}  # Use the AWS region from the environment variable

      - name: 'Set up SSH keys'
        run: |
          echo "${{ secrets.PRIVATE_KEY }}" > keys/la_maldita_llave.pem  # Create the private key file from the secret
          echo "${{ secrets.PUBLIC_KEY }}" > keys/la_maldita_llave.pub  # Create the public key file from the secret
          chmod 600 keys/llave.pem  # Set the appropriate permissions for the private key
          chmod 600 keys/llave.pub  # Set the appropriate permissions for the public key

      - name: 'Terraform Init'
        run: terraform init  # Initialize Terraform

      - name: 'Terraform Plan'
        run: terraform plan -out=tfplan  # Create a Terraform plan and output it to a file

      - name: 'Terraform Apply'
        if: github.ref == 'refs/heads/main'  # Only apply the plan if the branch is main
        run: terraform apply -auto-approve tfplan  # Apply the Terraform plan automatically